Document: vookiimageviewer
Title: Debian vookiimageviewer Manual
Author: <insert document author here>
Abstract: This manual describes what vookiimageviewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vookiimageviewer/vookiimageviewer.sgml.gz

Format: postscript
Files: /usr/share/doc/vookiimageviewer/vookiimageviewer.ps.gz

Format: text
Files: /usr/share/doc/vookiimageviewer/vookiimageviewer.text.gz

Format: HTML
Index: /usr/share/doc/vookiimageviewer/html/index.html
Files: /usr/share/doc/vookiimageviewer/html/*.html
