name: Windows Builds

on: 
  workflow_dispatch:
  workflow_call:
  push:
  
env:
  QT_VERSION:              "6.4.0"
  MINGW_VERSION:           "win64_msvc2019_64"
  BUILD_TYPE:              Release
  artifact_retention_days: 5

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        host: 'windows'
        target: 'desktop'
        modules: 'qtimageformats'        
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        dir: "${{github.workspace}}/qt"
        install-deps: "true"

    -
      name: build sources [configuration]
      working-directory: ${{github.workspace}}\..
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -A x64 -G "Visual Studio 17 2022" -Bbuild ${{github.workspace}}\build\cmake -Wno-dev
    -
      name: build sources
      working-directory: ${{github.workspace}}\..
      run: |
        cmake --build build --config ${{env.BUILD_TYPE}} --target package

        cd build
        $artifact_path = pwd
        echo "artifact_path=$artifact_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        $name = Get-Childitem -Filter *.zip -Name
        echo "artifact_name_zip=$name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        $name = Get-Childitem -Filter *.7z -Name
        echo "artifact_name_7z=$name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        $name = Get-Childitem -Filter *.msi -Name
        echo "artifact_name_msi=$name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
    - name: archive artifacts [zip]
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.artifact_name_zip}}
        path: |
          ${{env.artifact_path}}\${{env.artifact_name_zip}}
        retention-days: ${{ inputs.artifact_retention_days }}
    - name: archive artifacts [7z]
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.artifact_name_7z}}
        path: |
          ${{env.artifact_path}}\${{env.artifact_name_7z}}
        retention-days: ${{ inputs.artifact_retention_days }}
    - name: archive artifacts [msi]
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.artifact_name_msi}}
        path: |
          ${{env.artifact_path}}\${{env.artifact_name_msi}}
        retention-days: ${{ inputs.artifact_retention_days }}
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ${{env.artifact_path}}\${{env.artifact_name_zip}}
          ${{env.artifact_path}}\${{env.artifact_name_7z}}
          ${{env.artifact_path}}\${{env.artifact_name_msi}}
